name: xtyle
description: styling component by coders
version: 0.0.1
homepage: https://github.com/thedevsbuddy/tailwind_cli

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  logger: ^2.5.0

dev_dependencies:
  build_runner: ^2.4.11
  code_builder: ^4.10.0
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:


